[logger]
level = "debug"

[server]
# Disable protections since nginx handles security
enableCORS = true
corsAllowedOrigins = ['https://www.12taste.com/', 'https://12taste.com/']
enableXsrfProtection = false
enableWebsocketCompression = false

[client]
# Show detailed errors for debugging
showErrorDetails = true
